username: EMAIL HERE
password: GMAIL PASSWORD HERE

emails:
  - name: NAME
    email: EMAIL 
  - name: NAME2
    email: EMAIL2
  - name: NAME3
    email: EMAIL3 
  - name: NAME4
    email: EMAIL4
  - name: NAME5
    email: EMAIL5



    
